// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEtB6URc8SyTvVma4KO8Grqpr3vVrTFrM',
    appId: '1:1001347116011:web:c2a97facdada08045907ae',
    messagingSenderId: '1001347116011',
    projectId: 'quiz-app-project-8b369',
    authDomain: 'quiz-app-project-8b369.firebaseapp.com',
    storageBucket: 'quiz-app-project-8b369.firebasestorage.app',
    measurementId: 'G-9RYXKZVSZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvLXFoT8w2S6F8Ba-TNRXBLyi0N-c8wks',
    appId: '1:1001347116011:android:45ebc3b7a5b6f6705907ae',
    messagingSenderId: '1001347116011',
    projectId: 'quiz-app-project-8b369',
    storageBucket: 'quiz-app-project-8b369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMassKzh2jyaNcj5RMRyNMKGWqp_k6J5c',
    appId: '1:1001347116011:ios:cdc6bc3a19dcdfa95907ae',
    messagingSenderId: '1001347116011',
    projectId: 'quiz-app-project-8b369',
    storageBucket: 'quiz-app-project-8b369.firebasestorage.app',
    iosClientId: '1001347116011-uipmm7ohe8ucp9uau6do2rveh5nrn2a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMassKzh2jyaNcj5RMRyNMKGWqp_k6J5c',
    appId: '1:1001347116011:ios:cdc6bc3a19dcdfa95907ae',
    messagingSenderId: '1001347116011',
    projectId: 'quiz-app-project-8b369',
    storageBucket: 'quiz-app-project-8b369.firebasestorage.app',
    iosClientId: '1001347116011-uipmm7ohe8ucp9uau6do2rveh5nrn2a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEtB6URc8SyTvVma4KO8Grqpr3vVrTFrM',
    appId: '1:1001347116011:web:cdddd34ea7fbc6f55907ae',
    messagingSenderId: '1001347116011',
    projectId: 'quiz-app-project-8b369',
    authDomain: 'quiz-app-project-8b369.firebaseapp.com',
    storageBucket: 'quiz-app-project-8b369.firebasestorage.app',
    measurementId: 'G-PZM3Z84RP6',
  );
}
